from pathlib import Path

Import("env")


def parse_flat_toml(path):
    try:
        import tomllib

        with path.open("rb") as file:
            return tomllib.load(file)
    except ModuleNotFoundError:
        pass

    settings = {}
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()

        if not line or line.startswith("#"):
            continue

        if "=" not in line:
            raise ValueError(f"Invalid settings.toml line {line_number}: {raw_line}")

        key, raw_value = line.split("=", 1)
        key = key.strip()
        raw_value = raw_value.strip()

        if raw_value.lower() == "true":
            value = True
        elif raw_value.lower() == "false":
            value = False
        elif raw_value.startswith('"') and raw_value.endswith('"'):
            value = raw_value[1:-1]
        else:
            value = raw_value

        settings[key] = value

    return settings


def cpp_value(value):
    if isinstance(value, bool):
        return "true" if value else "false"

    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'

    return str(value)


project_dir = Path(env["PROJECT_DIR"])
settings_path = project_dir / "settings.toml"
output_path = project_dir / "src" / "generated_settings.h"

if not settings_path.exists():
    raise FileNotFoundError(
        "settings.toml was not found. Copy settings.example.toml to settings.toml first."
    )

settings = parse_flat_toml(settings_path)

lines = [
    "#pragma once",
    "",
    "// Generated from settings.toml by scripts/generate_settings.py.",
    "// Do not edit this file manually.",
    "",
]

for key, value in settings.items():
    lines.append(f"constexpr auto {key} = {cpp_value(value)};")

output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Generated {output_path}")
