HOME_WIFI_SSID = ""
HOME_WIFI_PASSWORD = ""

BACKUP_WIFI_SSID = ""
BACKUP_WIFI_PASSWORD = ""

AP_SSID="Alan Protogen"
AP_PASSWORD=""
DEVICE_HOSTNAME="protogen"


ACCELEROMETER_ON = true
MIC_ON = true
APDS_ON = true
BOOP_RAINBOW_ON = true
RAINBOW_OVERRIDE_ON = false
SSD1306_ON = true
WIFI_CONNECT_ON = false
WIFI_BROADCAST_ON = true
VERBOSE = false
    